### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by nitin-1926** [TechOUs/Join-TechOUs#2]
sample join request is given in this project repo issues please have a look on that.

## Why do you want to join this organisation

I want to become a part of this organisation as I want to contribute to Open Source and I want to start from here by contributing my codes in TechOUs/algOrithms repository. 

## LINKS

github profile link

https://github.com/nitin-1926

### Add gmail address

nitin171538.cse@chitkara.edu.in

## Add *screenshot* of the github profile

![Screenshot (4)](https://user-images.githubusercontent.com/44253685/70344468-d57eed80-187f-11ea-901e-806eaeed0882.png)

### Description
I am building an official website for the Patiala School For Deaf and Blind using Firebase.
### links
https://signup-29e25.web.app
It's still in development.
### screenshots
![Screenshot (5)](https://user-images.githubusercontent.com/44253685/70345033-0ad80b00-1881-11ea-8854-746a8bb18e23.png)
![Screenshot (6)](https://user-images.githubusercontent.com/44253685/70345035-0d3a6500-1881-11ea-9dd2-bcd2392efc25.png)
![Screenshot (7)](https://user-images.githubusercontent.com/44253685/70345041-10cdec00-1881-11ea-9944-ea7102d2c312.png)

## What are your plan after joining this organisation (which project you would like to contribute please mention).
I would like to contribute in TechOUs/algOrithms as well as techous.github.io.
Moreover I will be an active member and will try to contribute regularly
## NOTE

* Edit the details which are mentioned right template should be followed.
* If you miss any detail above then your join request will be cancelled
* If you use any abusive content in the org. then you will be banned.
* If you try to spoof or by using any other method then will also be banned
* If you don't do any work after joining then there are chances you might get warning mail and removed out of the org.

**Comment by GauravWalia19** [comment]
Invite sent.
