### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by pankhuri-52** [TechOUs/Join-TechOUs#3]
sample join request is given in this project repo issues please have a look on that.

## Why do you want to join this organisation

I like to contribute to open source so I want to join this organization as I see tremendous opportunity in this.

### Add github profile link

https://github.com/pankhuri-52

### Add gmail address

pankhuritrikha@gmail.com

## Add *screenshot* of the github profile
![Screenshot from 2019-12-07 13-14-34](https://user-images.githubusercontent.com/49311757/70371022-9db18d80-18f3-11ea-9ce9-632bbe5d8951.png)

### Description
I made a website called ShoutUp for helping Domestic Violence Victims and linking them to their nearest NGOs.
### links
https://github.com/pankhuri-52/ShoutUp

![Screenshot from 2019-12-07 13-17-06](https://user-images.githubusercontent.com/49311757/70371050-ec5f2780-18f3-11ea-932b-a295ff7254a0.png)
![Screenshot from 2019-12-07 13-17-09](https://user-images.githubusercontent.com/49311757/70371053-ed905480-18f3-11ea-9593-1eac5aa43633.png)

## What are your plan after joining this organisation (which project you would like to contribute please mention).
After joining I wish to contribute in TechOUs/algOrithms as well as TechOUs/techous.github.io
## NOTE

* Edit the details which are mentioned right template should be followed.
* If you miss any detail above then your join request will be cancelled
* If you use any abusive content in the org. then you will be banned.
* If you try to spoof or by using any other method then will also be banned
* If you don't do any work after joining then there are chances you might get warning mail and removed out of the org.

**Comment by GauravWalia19** [comment]
Sorry **ONCE YOU SATISFY OUR CRITERIA WE WILL MAIL YOU**.

Till keep contributing.

**Comment by pankhuri-52** [comment]
Thanks for replying to me. I want to tell you that I fulfill your criteria.
I have more than 300 commits but only 80 are public and rest are private.
Plz check the screenshot. It would be really nice if you do so. Thanks &
Regards.

**Comment by GauravWalia19** [comment]
This is open source organisation so private contributions are not counted towards our count of contributions.
