### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by pankhuri-52** [TechOUs/Join-TechOUs#4]
sample join request is given in this project repo issues please have a look on that.

## Why do you want to join this organisation

I like to contribute to open source so I want to join this organization as I see tremendous opportunity in this.

## LINKS

github profile link

https://github.com/pankhuri-52

gmail address

pankhuritrikha@gmail.com

## Add *screenshot* of the github profile

![Screenshot from 2019-12-07 13-14-34](https://user-images.githubusercontent.com/49311757/70371358-eff4ad80-18f7-11ea-9c07-d36b5e597ec2.png)

### Description
I made a website called ShoutUp for helping Domestic Violence Victims and linking them to their nearest NGOs.

### links
https://github.com/pankhuri-52/ShoutUp
### screenshots
![Screenshot from 2019-12-07 13-17-06](https://user-images.githubusercontent.com/49311757/70371369-0b5fb880-18f8-11ea-9ecb-98163b60833c.png)
![Screenshot from 2019-12-07 13-17-09](https://user-images.githubusercontent.com/49311757/70371370-0dc21280-18f8-11ea-86a6-357deb22f0ca.png)

## What are your plan after joining this organisation (which project you would like to contribute please mention).
After joining I wish to contribute in TechOUs/algOrithms as well as TechOUs/techous.github.io
## NOTE

* Edit the details which are mentioned right template should be followed.
* If you miss any detail above then your join request will be cancelled
* If you use any abusive content in the org. then you will be banned.
* If you try to spoof or by using any other method then will also be banned
* If you don't do any work after joining then there are chances you might get warning mail and removed out of the org.

**Comment by GauravWalia19** [comment]
You will receive an invite shortly.
